baseURL = "https://dbh-staff.github.io/"
languageCode = "en-us"
title = "A docs for new/old staff members of DBH!"
theme = "digitalgarden"

googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "Welcome to Staff Docs!"
  images = ['/images/dbh.png']

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Staff Rules'
  url = '/rules'
  weight = 2
[[menu.main]]
  name = 'Ticketing'
  url = '/ticket'
  weight = 3
[[menu.main]]
  name = 'Support'
  url = '/support'
  weight = 4
[[menu.main]]
  name = 'Other Important things you should know'
  url = '/other'
  weight = 5
[[menu.main]]
  name = 'Staff News'
  url = '/news'
  weight = 6
[[menu.main]]
  name = 'Staff Timeline'
  url = '/time'
  weight = 6
[[menu.main]]
  name = 'Current Staff'
  url = '/staff'
  weight = 7



[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com'
  weight = 2
[[menu.social]]
  name = 'Email'
  url = 'mailto:sus.com'
  weight = 8

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "fire"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
